version: '3.1'
services:
    webapp:
        build: webapp
        ports:
            - "8000:80"
        volumes:
            - ./webapp:/webapp
        restart: on-failure
        environment:
            DISPENSER_HOST: ${DISPENSER_HOST:-treatme.home}

    janus:
        build: .
        # ports:
        #     - "8188:8188"
        #     - "8189:8189"
        #     - "5002:5002/udp"
        #     - "5004:5004/udp"

        network_mode: host

    videosrc:
        build: gst
        volumes:
            - /dev/video0:/dev/video0
            - /dev/snd:/dev/snd
        environment:
            JANUS_SERVER:
            VIDEO_DEVICE:
            ALSA_DEVICE:
        privileged: true
